name: Kali-Light

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          sudo apt update
          #sudo apt upgrade
          wget https://http.kali.org/pool/main/k/kali-archive-keyring/kali-archive-keyring_2024.1_all.deb
          wget https://archive.kali.org/kali/pool/main/l/live-build/live-build_20230502+kali3_all.deb
          sudo apt install -y git live-build simple-cdd cdebootstrap curl debootstrap
          sudo dpkg -i kali-archive-keyring_2024.1_all.deb
          sudo dpkg -i live-build_20230502+kali3_all.deb
          
          cd /usr/share/debootstrap/scripts/
          echo "default_mirror http://http.kali.org/kali"; sed -e "s/debian-archive-keyring.gpg/kali-archive-keyring.gpg/g" sid > /tmp/kali
          sudo mv /tmp/kali .
          sudo ln -s kali kali-rolling444
          cd $GITHUB_WORKSPACE
          ./build.sh --variant light --arch amd64 --verbose
      - name: Compress
        run: |
          #7z a Kali-Linux.7z images/*.iso -mx1
  
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Kali-Linux
          path: images/*.iso
